version: '3.9'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-latest
    ports:
      - "3306:3306"
    expose:
      # Opens port 3306 on the container
      - '3306'
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
      #MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - ./mysql-data:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
    ports:
      - "3000:3000"
    environment:
      DB_HOST: mysql
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: db
      DB_PORT: 3306
    volumes:
      - ./logs:/app/logs
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
volumes: 
  mysql: